export const ACTIVITY_NAME_ORGANIZATION = [
    "CREATE_ORGANIZATION",
    "UPDATE_ORGANIZATION",
    "SET_OWNER_ORGANIZATION",
    "VERIFY_ORGANIZATION",
    "INVITE_USER_ORGANIZATION",
    "ACCEPT_ORGANIZATION_USER",
    "REMOVE_USER_ORGANIZATION",
    "ADD_ORGANIZATION_CHAPTER",
    "REMOVE_ORGANIZATION_CHAPTER"
]